name: Waka Readme

on:
  workflow_dispatch:
  schedule:   
    - cron: "0 0 * * *" # Runs at 12am UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          BLOCKS: "⬜🟨🟩"
          SHOW_TITLE: true
          SHOW_TIME: false
